Update assessment to include SQL Refinement
actblue/fec-data-interview-problem pull request #2
Opened 2022-10-06 20:01 UTC by sarahmathey

2022-10-06 20:07 UTC, eschick36 requested changes

2022-10-06 20:07 UTC, eschick36 commented on README.md
> +  - This query is a messy version of the query we used to pull the data used in exercise two of this take home. All of the where clauses, and table sources are correct and don’t need to be updated, b
Is it too obvious to say "uses CTEs and subqueries inconsistently"? Maybe we just say "has inconsistent syntax"?

2022-10-06 23:20 UTC, dstern04 approved these changes

2022-10-06 23:20 UTC, dstern04 commented on README.md
> +3. We’re not looking for award winning visualizations, if you chose to generate a visualization feel free to use the default plot style
```suggestion
3. We’re not looking for award winning visualizations, if you chose to generate a visualization feel free to use the default plot style
```
```suggestion
3. We’re not looking for award-winning visualizations, if you chose to generate a visualization feel free to use the default plot style
```

2022-10-06 23:20 UTC, dstern04 commented on README.md
> +**Objective**: Refine [this SQL Query](https://docs.google.com/document/d/1idPKfrhwhuw5C5qDMwWun0MI5wQaBI288RFMafcTDos/edit?usp=sharing) so that it is easily readable by your teammates and fix any sy
thoughts on "refine" vs "refactor"?

2022-10-06 23:20 UTC, dstern04 commented on README.md
> +3. We’re not looking for award winning visualizations, if you chose to generate a visualization feel free to use the default plot style
```suggestion
3. We’re not looking for award-winning visualizations, if you chose to generate a visualization feel free to use the default plot style
```

2022-10-07 13:27 UTC, eschick36 commented on README.md
> +**Objective**: Refine [this SQL Query](https://docs.google.com/document/d/1idPKfrhwhuw5C5qDMwWun0MI5wQaBI288RFMafcTDos/edit?usp=sharing) so that it is easily readable by your teammates and fix any sy
I like refactor!

2022-10-07 14:01 UTC, eschick36 approved these changes

2022-10-07 14:07 UTC, dstern04 approved these changes

2022-10-07 14:13 UTC, merged